
include: package:lints/recommended.yaml

linter:
  rules:
    file_names: false
    curly_braces_in_flow_control_structures: false
    prefer_relative_imports: true
    avoid_print: false
    avoid_unused_constructor_parameters: false
    prefer_single_quotes: false
    prefer_double_quotes: true