name: zst_block_format
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  es_compression: ^2.0.10
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
